# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
  - 3.8
  - 3.7
  - 3.6

install:
  - pip install -r requirements.txt -r requirements_dev.txt

script:
  - pytest
