# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
  - 3.8
  - 3.7
  - 3.6

stages:
  - check
  - test
  - deploy

install:
  - pip install -r requirements.txt -r requirements_dev.txt

script:
  - pytest

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: $PYPI_USER
  password:
    secure: $PYPI_PASSWORD
  on:
    tags: true

jobs:
  include:
    - stage: check
      name: Check with flake8
      script: flake8
      python: 3.8
