# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
  - 3.8
  - 3.7
  - 3.6

stages:
  - check
  - test

install:
  - pip install -r requirements.txt pytest

script:
  - pytest

jobs:
  include:
    - stage: check
      name: Check with flake8
      install: pip install flake8
      script: flake8
      python: 3.8

after_script:
  - if [ -f .coverage ]; then
      python -m pip install codecov;
      codecov;
    fi
